version: '3'
services:
        web:
                image: jame_v2
                build: .
                ports:
                        - "8095:8080"
                volumes:
                        - persistent_volume:/app/volumes
                restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/p3_jame/volumes





